# Generated by Django 5.1.3 on 2024-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_liftprofile_user_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
