# Generated by Django 5.1.3 on 2024-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_liftprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpeg', upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
