# Generated by Django 5.1.3 on 2024-12-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
